#pragma once

#define USB_POLLING_INTERVAL_MS 1

#define TAPPING_TERM 150
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT

#define ONESHOT_TAP_TOGGLE 2
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

#define USE_SERIAL
#define EE_HANDS

#define RGBLIGHT_SLEEP
#define RGBLIGHT_LAYERS
