#pragma once

#define TAPPING_TERM 180
#define IGNORE_MOD_TAP_INTERRUPT

#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 5000

#define USE_SERIAL
#define EE_HANDS

#define RGBLIGHT_SLEEP
#define RGBLIGHT_LAYERS
#undef RGBLIGHT_ANIMATIONS
