#pragma once

#define USB_POLLING_INTERVAL_MS 1

#define TAPPING_TERM 200
#define HOLD_ON_OTHER_KEY_PRESS

#define ONESHOT_TAP_TOGGLE 2
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define EE_HANDS
#define USB_VBUS_PIN GP19
