#pragma once

#define USB_POLLING_INTERVAL_MS 1

#define TAPPING_TERM 150
#define QUICK_TAP_TERM_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define ONESHOT_TAP_TOGGLE 2
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define EE_HANDS
#define USB_VBUS_PIN GP19
