#pragma once

#define USB_POLLING_INTERVAL_MS 1

#define TAPPING_TERM 150
#define TAPPING_TERM_PER_KEY

#define PERMISSIVE_HOLD

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 0

#define EE_HANDS
#define USB_VBUS_PIN GP19
